name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
            ${{ runner.os }}-
      - name: Create virtual environment.
        run: |
          python -m venv venv
      - name: Install dependencies.
        run: |
          . venv/bin/activate
          make pydep
      - name: Install cape package.
        run: |
          . venv/bin/activate
          make pylib
      - name: Lint check the cape package.
        run: |
          . venv/bin/activate
          make lint
      - name: Test cape.
        run: |
          . venv/bin/activate
          make test-ci

  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
