name: PyCape CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Isolate in a virtual environment.
        run: |
          python -m venv venv
      - name: Install dev dependencies.
        run: |
          . venv/bin/activate
          make pydep
      - name: Install PyCape package.
        run: |
          . venv/bin/activate
          make pylib
      - name: Lint PyCape.
        run: |
          . venv/bin/activate
          make lint
      - name: Test PyCape.
        run: |
          . venv/bin/activate
          make test

  release-notes:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
