name: Serdio CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      serdio/*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No changes to Serdio, CI not required" '